# Project information
site_name: 'Accompanist'
site_description: 'A group of libraries to help write Jetpack Compose apps.'
site_author: 'Google'
site_url: 'https://google.github.io/accompanist/'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

docs_dir: docs-gen

# Repository
repo_name: 'Accompanist'
repo_url: 'https://github.com/google/accompanist'

# Navigation
nav:
  - 'Overview': index.md
  - 'System UI Controller':
    - 'Guide': systemuicontroller.md
    - 'API': api/systemuicontroller/
  - 'Drawable Painter':
    - 'Guide': drawablepainter.md
    - 'API': api/drawablepainter/ 
  - 'Permissions':
    - 'Guide': permissions.md
    - 'API': api/permissions/
  - 'Navigation Animation':
      - 'Guide': navigation-animation.md
      - 'API': api/navigation-animation/
  - 'Navigation Material':
      - 'Guide': navigation-material.md
      - 'API': api/navigation-material/
  - 'Adaptive':
      - 'Guide': adaptive.md
      - 'API': api/adaptive
  - 'Snapshots': using-snapshot-version.md
  - 'Contributing': contributing.md
  - 'Maintainers':
    - 'Update guide': updating.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/music-clef-treble
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
